CREATE TABLE marca (
    id_marca INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    codigo_marca VARCHAR(20) NOT NULL UNIQUE,
    nombre_marca VARCHAR(100) NOT NULL,
    name_marca VARCHAR(100) NOT NULL COMMENT 'Nombre en inglés',
    descr_marca VARCHAR(255),
    activo_marca BOOLEAN DEFAULT TRUE,
    created_at_marca TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at_marca TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;